package ui

import (
	"strings"

	"github.com/asheshgoplani/agent-deck/internal/session"
)

// primaryKind tags which field won the precedence contest for a row's
// primary label. The render path styles each kind differently (branch =
// purple, folder = its worktree color, broadcast/auto = dim, name = the
// status-based title style).
type primaryKind int

const (
	primaryNone      primaryKind = iota
	primaryName                  // user-chosen session title
	primaryBranch                // distinguishing git branch
	primaryFolder                // worktree / project folder
	primaryBroadcast             // live Claude pane title
	primaryAuto                  // adjective-noun auto name (last resort)
)

// primaryLabel is the chosen identity for a session row: the unstyled
// display text plus the kind that won, so the renderer knows how to color
// it and whether the separate worktree chip would be redundant.
type primaryLabel struct {
	text string
	kind primaryKind
}

// baseBranches are branch names that don't distinguish a session — shared
// trunks and this fork's working branch. A session sitting on one of these
// falls through to its folder/name instead of showing the branch.
var baseBranches = map[string]struct{}{
	"main":    {},
	"master":  {},
	"develop": {},
	"dev":     {},
	"trunk":   {},
	"local":   {},
}

func isBaseBranch(branch string) bool {
	_, ok := baseBranches[strings.ToLower(branch)]
	return ok
}

// nameFirstWorktreePrefixes are worktree keys where NEITHER the branch nor
// the folder identifies the session, so both are skipped in favor of the
// session's own name / Claude's live activity. ro-dev (read-only dev)
// checkouts ride whatever feature branch is under review and the folder is
// the same across them, so showing the branch or "ro-dev" is useless — the
// user wants the session name or what Claude is doing. Add more prefixes
// here if other worktree types behave the same way.
var nameFirstWorktreePrefixes = []string{"ro-dev"}

// isNameFirstWorktree reports whether key belongs to a worktree where the
// label should come from the session name / broadcast rather than the
// branch or folder.
func isNameFirstWorktree(key string) bool {
	for _, p := range nameFirstWorktreePrefixes {
		if key == p || strings.HasPrefix(key, p) {
			return true
		}
	}
	return false
}

// primaryLabelFor picks the most-distinguishing label for a session by
// dynamic precedence (see the model the user approved):
//
//  1. Custom name      — title that isn't an auto adjective-noun.
//  2. Distinguishing    — git branch that's unique among visible sessions
//     branch              and not a base/trunk branch (→ workers).
//  3. Claude broadcast  — the live pane title (what the agent is doing now).
//  4. Folder/worktree   — worker-N, ro-dev-2, repo basename.
//  5. Auto name         — adjective-noun, absolute last resort.
//
// branchCount is the per-render tally of how many visible sessions sit on
// each branch; a count > 1 means the branch is shared (e.g. several ro-dev
// sessions on one branch) and therefore non-distinguishing.
func primaryLabelFor(inst *session.Instance, st sessionRenderState, branchCount map[string]int) primaryLabel {
	if inst == nil {
		return primaryLabel{}
	}

	// 1. Meaningful, user-chosen title (wins everywhere, including ro-dev).
	// Strip a leading "MAIA-<number>" ticket prefix so titles named after a
	// Linear ticket (e.g. "MAIA-2213 migrate user-field") scan by number.
	if inst.Title != "" && !session.IsAutoGeneratedName(inst.Title) {
		return primaryLabel{text: stripMaiaTicketPrefix(inst.Title), kind: primaryName}
	}

	key := worktreeKey(inst)

	// 1b. Name-first worktrees (ro-dev): the branch and folder don't
	// distinguish the session, so skip straight to Claude's live activity,
	// then the auto name — never the branch or the bare folder.
	if isNameFirstWorktree(key) {
		if st.paneTitle != "" {
			return primaryLabel{text: st.paneTitle, kind: primaryBroadcast}
		}
		if inst.Title != "" {
			return primaryLabel{text: inst.Title, kind: primaryAuto}
		}
		// Nothing else to show — fall back to the folder so it isn't nameless.
		if key != "" {
			return primaryLabel{text: key, kind: primaryFolder}
		}
		return primaryLabel{}
	}

	// 2. A branch that actually identifies this session.
	if b := st.branch; b != "" && !isBaseBranch(b) && branchCount[b] <= 1 {
		return primaryLabel{text: cleanBranchDisplay(b), kind: primaryBranch}
	}

	// 3. Whatever Claude is broadcasting right now. Live activity beats the
	// static folder name — for a worker the user wants to see what it's doing,
	// not which interchangeable worktree it happens to occupy. The folder is
	// still surfaced as the color-coded worktree chip alongside this label.
	if st.paneTitle != "" {
		return primaryLabel{text: st.paneTitle, kind: primaryBroadcast}
	}

	// 4. The worktree / folder it lives in (fallback when nothing is live).
	if key != "" {
		return primaryLabel{text: key, kind: primaryFolder}
	}

	// 5. Fall back to the auto name so the row is never nameless.
	if inst.Title != "" {
		return primaryLabel{text: inst.Title, kind: primaryAuto}
	}
	return primaryLabel{}
}
